# Generated by Django 5.0 on 2024-01-02 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TravelWebApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel",
            name="city",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="travel",
            name="city_picture",
            field=models.ImageField(blank=True, null=True, upload_to="city_images"),
        ),
        migrations.AddField(
            model_name="travel",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="travel",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="travel",
            name="number_of_people",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="travel",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="travel",
            name="type_of_transport",
            field=models.CharField(
                choices=[("car", "Car"), ("plane", "Plane"), ("other", "Other")],
                default=("plane", "Plane"),
                max_length=10,
            ),
        ),
    ]
