# Generated by Django 5.0 on 2024-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TravelWebApp",
            "0002_travel_city_travel_city_picture_travel_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="type_of_transport",
            field=models.CharField(
                choices=[("car", "Car"), ("plane", "Plane"), ("other", "Other")],
                default=("car", "Car"),
                max_length=10,
            ),
        ),
    ]
