# Generated by Django 5.0 on 2024-01-02 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TravelWebApp", "0004_alter_travel_end_date_alter_travel_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 9, 19, 6, 35, 700191, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 2, 19, 6, 35, 699969, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
