# Generated by Django 5.0 on 2024-01-08 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TravelWebApp", "0005_alter_travel_end_date_alter_travel_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel",
            name="country",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="travel",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 15, 11, 23, 59, 470278, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 8, 11, 23, 59, 470104, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
