# Generated by Django 5.0 on 2024-01-11 21:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TravelWebApp", "0008_remove_task_due_date_alter_travel_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="travel",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="TravelWebApp.travel",
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 18, 21, 29, 59, 996596, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 11, 21, 29, 59, 996416, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
