# Generated by Django 5.0 on 2024-01-11 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TravelWebApp", "0009_task_travel_alter_travel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 18, 21, 34, 33, 994684, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 11, 21, 34, 33, 994503, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
