# Generated by Django 5.0 on 2024-01-13 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TravelWebApp", "0013_alter_task_description_alter_travel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="travel",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 20, 17, 39, 20, 122703, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 13, 17, 39, 20, 122485, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
